image: docker:latest

stages:
- docker_build

variables:
    DEVELOPMENT_IMAGE: registry.git-ce.rwth-aachen.de/ebc/projects/ebc_acs0017_bmwi_agent/agents_python/agentlib:latest
    CLONEMAP_IMAGE: registry.git-ce.rwth-aachen.de/ebc/projects/ebc_acs0017_bmwi_agent/agents_python/agentlib:clonemap
    DOCKER_DRIVER: overlay

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_agentlib:
    stage: docker_build
    services:
      - docker:18.09.7-dind
    script:
        - docker build --pull -f ci/agentlib/Dockerfile -t $DEVELOPMENT_IMAGE .
        - docker push $DEVELOPMENT_IMAGE
        - docker build --pull -f ci/clonemap/Dockerfile -t $CLONEMAP_IMAGE .
        - docker push $CLONEMAP_IMAGE
    only:
       - main
